services:
  api:
    image: coffresh-api
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/app/src
    env_file:
      - backend/.env
    environment:
      # - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/coffresh

  frontend:
    image: coffresh-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  tests:
    image: coffresh-api
    depends_on:
      - api
      # - mongodb
    volumes:
      - ./backend/src/test.js:/app/src/test.js
    #environment:
    # - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
    # - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/coffresh
    # - NODE_ENV=test

    # working_dir: /app
    command: node ./src/test.js
