services:
  api:
    image: coffresh-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      # - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/coffresh

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  tests:
    image: coffresh-api
    depends_on:
      - api
    volumes:
      - ./src/test.js:/app/src/test.js
    #environment:
    # - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
    # - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/coffresh
    # - NODE_ENV=test

    # working_dir: /app
    command: node ./src/test.js
