services:
  api:
    image: coffresh-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      # - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/coffresh

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  tests:
    image: node:14
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: node src/test.js
